apiVersion: v1
kind: Service
metadata:
  name: user-svc
  labels:
    app: user-svc
spec:
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
  selector:
    app: user-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-svc
  labels:
    app: user-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-svc
  template:
    metadata:
      labels:
        app: user-svc
    spec:
      containers:
      - name: user-svc
        image: user-svc:latest
        ports:
        - containerPort: 50051
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: user-svc-config
              key: db_host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: user-svc-config
              key: db_port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: user-svc-config
              key: db_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: user-svc-secrets
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-svc-secrets
              key: db_password
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: user-svc-secrets
              key: jwt_secret_key
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-svc-config
data:
  db_host: "postgres-service"
  db_port: "5432"
  db_name: "user_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: user-svc-secrets
type: Opaque
data:
  db_user: cG9zdGdyZXM=  # postgres
  db_password: cGFzc3dvcmQ=  # password
  jwt_secret_key: c2VjcmV0LWtleQ==  # secret-key 